# Generated by Django 3.1.2 on 2020-11-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='zipcode',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='State',
            new_name='state',
        ),
    ]
