# Generated by Django 3.1.2 on 2020-11-10 06:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import donation.models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='main_image',
            field=models.ImageField(null=True, upload_to=donation.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=donation.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_img', to='donation.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='donation.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='donation.category'),
        ),
    ]
