# Generated by Django 3.1.2 on 2020-11-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20201120_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='approximate',
            field=models.BooleanField(default=True),
        ),
    ]
