# Generated by Django 3.1.2 on 2020-11-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_location_approximate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
    ]
