# Generated by Django 3.1.2 on 2020-11-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_remove_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to='donation.post'),
        ),
    ]
