# Generated by Django 3.1.2 on 2020-11-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_auto_20201110_1232_squashed_0009_auto_20201111_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Special Note/Instruction'),
        ),
    ]
