# Generated by Django 3.1.2 on 2020-11-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_auto_20201120_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to='donation.post'),
        ),
    ]
