# Generated by Django 3.1.2 on 2020-11-18 09:11

from django.db import migrations, models
import donation.models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='main_image',
        ),
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.ImageField(null=True, upload_to=donation.models.user_directory_path),
        ),
    ]
