# Generated by Django 3.1.2 on 2020-11-18 09:49

from django.db import migrations, models
import donation.models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_auto_20201118_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(null=True, upload_to=donation.models.main_directory_path),
        ),
    ]
