# Generated by Django 3.1.2 on 2020-11-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_post_bookmarked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bookmarked',
        ),
    ]
