# Generated by Django 3.1.2 on 2020-11-28 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation', '0009_remove_post_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
