# Generated by Django 3.1.2 on 2020-11-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201117_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
